#base-image for node on any machine using a template var
FROM resin/%%RESIN_MACHINE_NAME%%-node:5.7.1

# install deps on build server, making sure to clean up the artifacts it creates in order to reduce the image size.
RUN npm install

# copy all files to /usr/src/app  dir
COPY . /usr/src/app

# Run server when container runs on device
CMD ["bash", "/usr/src/app/start.sh"]
